In [1]:
import numpy as np

In [3]:
j=[4,6,2,8,9]

In [11]:
j=[5,7,2,8,4,7]
j

[5, 7, 2, 8, 4, 7]

In [13]:
np.array(j)

array([5, 7, 2, 8, 4, 7])

In [15]:
tuple(j)

(5, 7, 2, 8, 4, 7)

In [17]:
d=np.array(j)
d

array([5, 7, 2, 8, 4, 7])

In [19]:
type(d)

numpy.ndarray

In [21]:
d.shape

(6,)

In [23]:
d.ndim

1

In [25]:
d.size

6

In [27]:
s=[[4,8,90,12],[56,78,54,20],[67,89,50,49],[77,88,22,55],[90,40,70,60]]
s

[[4, 8, 90, 12],
 [56, 78, 54, 20],
 [67, 89, 50, 49],
 [77, 88, 22, 55],
 [90, 40, 70, 60]]

In [29]:
type(s)

list

In [31]:
arr1=np.array(s)
arr1

array([[ 4,  8, 90, 12],
       [56, 78, 54, 20],
       [67, 89, 50, 49],
       [77, 88, 22, 55],
       [90, 40, 70, 60]])

In [33]:
arr1.shape

(5, 4)

In [35]:
arr1.size

20

In [37]:
arr1.ndim

2

In [39]:
h=d.reshape(2,3)
h

array([[5, 7, 2],
       [8, 4, 7]])

In [41]:
h.size

6

In [43]:
h.shape

(2, 3)

In [45]:
h.ndim

2

In [47]:
w=d.reshape(3,2)
w

array([[5, 7],
       [2, 8],
       [4, 7]])

In [49]:
w.shape

(3, 2)

In [51]:
w.size

6

In [53]:
w.ndim

2

In [55]:
d

array([5, 7, 2, 8, 4, 7])

In [57]:
d.ndim

1

In [59]:
d.size

6

In [61]:
d.shape

(6,)

In [63]:
arr1.shape

(5, 4)

In [65]:
arr1.reshape(2,2,5)

array([[[ 4,  8, 90, 12, 56],
        [78, 54, 20, 67, 89]],

       [[50, 49, 77, 88, 22],
        [55, 90, 40, 70, 60]]])

In [67]:
k=arr1.reshape(2,2,5)
k

array([[[ 4,  8, 90, 12, 56],
        [78, 54, 20, 67, 89]],

       [[50, 49, 77, 88, 22],
        [55, 90, 40, 70, 60]]])

In [69]:
k.size

20

In [71]:
k.ndim

3

In [73]:
k.shape

(2, 2, 5)

In [75]:
y=arr1.reshape(20,)
y

array([ 4,  8, 90, 12, 56, 78, 54, 20, 67, 89, 50, 49, 77, 88, 22, 55, 90,
       40, 70, 60])

In [77]:
y.ndim

1

In [79]:
y.shape

(20,)

In [81]:
z=arr1.reshape(20,1)
z

array([[ 4],
       [ 8],
       [90],
       [12],
       [56],
       [78],
       [54],
       [20],
       [67],
       [89],
       [50],
       [49],
       [77],
       [88],
       [22],
       [55],
       [90],
       [40],
       [70],
       [60]])

In [83]:
z.ndim

2

In [85]:
z=arr1.reshape(1,20)
z

array([[ 4,  8, 90, 12, 56, 78, 54, 20, 67, 89, 50, 49, 77, 88, 22, 55,
        90, 40, 70, 60]])

In [87]:
z.ndim

2

In [89]:
arr1.reshape(2,2,5,1)

array([[[[ 4],
         [ 8],
         [90],
         [12],
         [56]],

        [[78],
         [54],
         [20],
         [67],
         [89]]],


       [[[50],
         [49],
         [77],
         [88],
         [22]],

        [[55],
         [90],
         [40],
         [70],
         [60]]]])

In [91]:
arr1.reshape(1,2,1,2,5,1)

array([[[[[[ 4],
           [ 8],
           [90],
           [12],
           [56]],

          [[78],
           [54],
           [20],
           [67],
           [89]]]],



        [[[[50],
           [49],
           [77],
           [88],
           [22]],

          [[55],
           [90],
           [40],
           [70],
           [60]]]]]])

In [93]:
range(5,20)

range(5, 20)

In [95]:
m=[3,4,5,6,7,8,9,10,11,12]
m

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [97]:
range(3,13)

range(3, 13)

In [99]:
list(range(3,13,2))

[3, 5, 7, 9, 11]

In [101]:
range(5,500)

range(5, 500)

In [103]:
tuple(range(5,500))

(5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 1

In [105]:
tuple(range(5,500,100))

(5, 105, 205, 305, 405)

In [107]:
tuple(range(5,506,100))

(5, 105, 205, 305, 405, 505)

In [109]:
list(range(-10,1))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

In [111]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [113]:
list(range(-1,-10,-2))

[-1, -3, -5, -7, -9]

In [115]:
list(range(10,-10,-2))

[10, 8, 6, 4, 2, 0, -2, -4, -6, -8]

In [117]:
[2.5,3,3.5,4,4.5]

[2.5, 3, 3.5, 4, 4.5]

In [119]:
np.arange(2.5,5,0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [121]:
np.arange(5,10,1)

array([5, 6, 7, 8, 9])

In [123]:
range(5,50,5)

range(5, 50, 5)

In [125]:
for i in range(5,50,5):
    print("Data")

Data
Data
Data
Data
Data
Data
Data
Data
Data


In [127]:
for i in range(5,50,5):
    print("Data",i)

Data 5
Data 10
Data 15
Data 20
Data 25
Data 30
Data 35
Data 40
Data 45


In [129]:
j=[5,87,23,46,62,84,80,45,77,33,80]
j

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [131]:
even_index= [j[i] for i in range(len(j)) if i % 2 == 0]
odd_index= [j[i] for i in range(len(j)) if i % 2 != 0]
print("Even index:", even_index)
print("Odd index :", odd_index)


Even index: [5, 23, 62, 80, 77, 80]
Odd index : [87, 46, 84, 45, 33]


In [133]:
j=[5,87,23,46,62,84,80,45,77,33,80]
j

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [135]:
x=[]
y=[]
for i in range(len(j)):
    if i%2==0:
        x.append(j[i])
    else:
        y.append(j[i])

In [137]:
for i in j:
    print(i)

5
87
23
46
62
84
80
45
77
33
80


In [139]:
range(len(j))

range(0, 11)

In [141]:
for i in range(len(j)):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
