In [1]:
import pandas as pd
import numpy as np

In [3]:
a=np.random.randint(20,60,15)
a

array([52, 48, 58, 20, 55, 41, 37, 42, 29, 23, 57, 58, 27, 47, 47])

In [5]:
a

array([52, 48, 58, 20, 55, 41, 37, 42, 29, 23, 57, 58, 27, 47, 47])

In [7]:
a[-5:-12]

array([], dtype=int32)

In [9]:
a[-5:-12:-1]

array([57, 23, 29, 42, 37, 41, 55])

In [11]:
a.ndim

1

In [13]:
a[-4]

58

In [15]:
np.random.seed(94)
b=np.random.randint(45,78,(7,6))

In [17]:
b

array([[63, 45, 48, 67, 74, 64],
       [61, 53, 61, 59, 55, 77],
       [69, 69, 48, 60, 71, 56],
       [51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53],
       [60, 55, 64, 72, 46, 69],
       [65, 75, 75, 51, 75, 67]])

In [19]:
b.ndim

2

In [21]:
b[0]

array([63, 45, 48, 67, 74, 64])

In [23]:
b[:,4]

array([74, 55, 71, 68, 65, 46, 75])

In [25]:
b[1,3]

59

In [27]:
b[2] #2nd row

array([69, 69, 48, 60, 71, 56])

In [29]:
b[:,]

array([[63, 45, 48, 67, 74, 64],
       [61, 53, 61, 59, 55, 77],
       [69, 69, 48, 60, 71, 56],
       [51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53],
       [60, 55, 64, 72, 46, 69],
       [65, 75, 75, 51, 75, 67]])

In [31]:
np.random.seed(94)
b=np.random.randint(45,78,(7,6))

In [33]:
b

array([[63, 45, 48, 67, 74, 64],
       [61, 53, 61, 59, 55, 77],
       [69, 69, 48, 60, 71, 56],
       [51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53],
       [60, 55, 64, 72, 46, 69],
       [65, 75, 75, 51, 75, 67]])

In [35]:
b[2]#2nd row

array([69, 69, 48, 60, 71, 56])

In [37]:
b[:,4]

array([74, 55, 71, 68, 65, 46, 75])

In [39]:
b[1,3]#1 st row and 3 column position

59

In [41]:
b[1,4]

55

In [43]:
b[2,]

array([69, 69, 48, 60, 71, 56])

In [45]:
b[5]

array([60, 55, 64, 72, 46, 69])

In [47]:
b[2,1:6]

array([69, 48, 60, 71, 56])

In [49]:
array[ row_start : row-end : row-step]

NameError: name 'array' is not defined

In [51]:
b[2:4:2,1:6]

array([[69, 48, 60, 71, 56]])

In [53]:
array [ row_start : row-end : row-step , col_start : col_end : col_step]


NameError: name 'array' is not defined

In [55]:
b[2:5,2:6]

array([[48, 60, 71, 56],
       [59, 47, 68, 77],
       [52, 74, 65, 53]])

In [57]:
b

array([[63, 45, 48, 67, 74, 64],
       [61, 53, 61, 59, 55, 77],
       [69, 69, 48, 60, 71, 56],
       [51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53],
       [60, 55, 64, 72, 46, 69],
       [65, 75, 75, 51, 75, 67]])

In [59]:
b[1:6:2]

array([[61, 53, 61, 59, 55, 77],
       [51, 58, 59, 47, 68, 77],
       [60, 55, 64, 72, 46, 69]])

In [61]:
b[1:6:2, 1:8:3]

array([[53, 55],
       [58, 68],
       [55, 46]])